"""changed votes to only be upvotes

Revision ID: 2a713aac2171
Revises: a3fe265e1d96
Create Date: 2022-03-30 14:44:48.623346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a713aac2171'
down_revision = 'a3fe265e1d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vote', schema=None) as batch_op:
        batch_op.drop_column('voteType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voteType', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
