"""fixed recipe

Revision ID: a3fe265e1d96
Revises: fd7543c53de9
Create Date: 2022-03-29 00:23:47.923679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fe265e1d96'
down_revision = 'fd7543c53de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
