"""added chef col

Revision ID: fd7543c53de9
Revises: e30103521104
Create Date: 2022-03-29 00:09:47.025294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7543c53de9'
down_revision = 'e30103521104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chef', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
